<?php declare(strict_types = 1);
require_once __DIR__ . '/../vendor/autoload.php';

$exclude = 'XDG_SEAT|XDG_SESSION_ID|LC_IDENTIFICATION|GIO_LAUNCHED_DESKTOP_FILE_PID|' .
    'GNOME_KEYRING_CONTROL|GNOME_DESKTOP_SESSION_ID|DEFAULTS_PATH|QT_QPA_PLATFORMTHEME|JAVA_HOME|' .
    'PAPERSIZE|IM_CONFIG_PHASE|QT4_IM_MODULE|CLUTTER_IM_MODULE|XMODIFIERS|SSH_AUTH_SOCK|' .
    'XDG_SESSION_PATH|XAUTHORITY|XDG_SESSION_DESKTOP|GDMSESSION|QT_IM_MODULE|GIO_LAUNCHED_DESKTOP_FILE|' .
    'UPSTART_EVENTS|XDG_CONFIG_DIRS|MANDATORY_PATH|UPSTART_SESSION|LIBVIRT_DEFAULT_URI|DESKTOP_SESSION|XDG_RUNTIME_DIR|' .
    'GTK_IM_MODULE|GTK_MODULES|IBUS_DISABLE_SNOOPER|TERMINATOR_UUID|UPSTART_INSTANCE|QT_ACCESSIBILITY|' .
    'ORBIT_SOCKETDIR|XDG_SEAT_PATH|XDG_DATA_DIRS|COMPIZ_BIN_PATH|COMPIZ_CONFIG_PROFILE|XDG_GREETER_DATA_DIR|' .
    'GTK2_MODULES|GPG_AGENT_INFO|SHLVL|XDG_VTNR|GDM_LANG|SESSIONTYPE|XDG_SESSION_TYPE|DBUS_SESSION_BUS_ADDRESS|' .
    'XDG_CURRENT_DESKTOP|GNOME_KEYRING_PID|QT_LINUX_ACCESSIBILITY_ALWAYS_ON|LSCOLORS|' .
    'RANCHER_URL|RANCHER_ACCESSS_KEY|RANCHER_SECRET_KAY|PHPBREW_HOME|PHPBREW_ROOT|PHPBREW_LOOKUP_PREFIX|PHPBREW_PHP|PHPBREW_PATH|' .
    'PATH_WITHOUT_PHPBREW|PHPBREW_BIN|PHPBREW_VERSION_REGEX|UPSTART_JOB';

foreach (\explode('|', $exclude) as $key) {
    unset($_SERVER[$key]);
}
\ksort($_SERVER);
